// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTgRyYLVDV17WCyO_zmhXarm9vNkLvRk',
    appId: '1:851572571996:web:5bdc82f88f0a72a1e90b99',
    messagingSenderId: '851572571996',
    projectId: 'almohandes-engineer-2026',
    authDomain: 'almohandes-engineer-2026.firebaseapp.com',
    storageBucket: 'almohandes-engineer-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDw3EJf2ahckQ3xVq_EOnD42zAp1_iIY',
    appId: '1:851572571996:android:370987dff44e3231e90b99',
    messagingSenderId: '851572571996',
    projectId: 'almohandes-engineer-2026',
    storageBucket: 'almohandes-engineer-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-NPyIMJqEqXJliVKU3BHpOugR0fOJLU',
    appId: '1:851572571996:ios:97d8d3ed202aa123e90b99',
    messagingSenderId: '851572571996',
    projectId: 'almohandes-engineer-2026',
    storageBucket: 'almohandes-engineer-2026.firebasestorage.app',
    iosBundleId: 'com.almohandes.app',
  );
}
